title: Terraform Intro
description: Demo for the Oracle Resource Manager
stackDescription: "Deploy ADB, Compute and Networking resources"
schemaVersion: 1.1.0
version: "20210925"
locale: "en"

source:
  type: image

outputGroups:
  - title: Access Information for Compute and ADB
    outputs:
      - ${demo_vm}
      - ${adb}

variableGroups:
  - title: Tenancy Configuration
    visible: false
    variables:
    - compartment_ocid
    - tenancy_ocid
    - region

variables:
  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: Compartment
    description: "Compartment where you want to create the FPP target and server"

  region:
    type: oci:identity:region:name
    required: true
    title: Region
    description: Region where you want to deploy the resources defined by this stack

outputs:
  adb:
    type: string
    title: Autonomous Database access
    displayText: Autonomous Database link to Database Actions
    visible: true

  demo_vm:
    type: string
    title: Compute instance access
    displayText: Public IP of the compute instance
    visible: true
